# Generated by Django 4.1 on 2022-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MGMT', 'MGMT'), ('SALES', 'SALES'), ('SUPPORT', 'SUPPORT')], default='MGMT', max_length=7),
        ),
    ]
