# Generated by Django 4.1 on 2022-08-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='client',
            new_name='customer',
        ),
    ]
