# Generated by Django 4.1 on 2022-08-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contract_client_alter_contract_sales_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='sales_contact',
            new_name='salesman',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='sales_contact',
            new_name='salesman',
        ),
    ]
