# Generated by Django 4.0.4 on 2022-08-13 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_rename_sales_contact_contract_salesman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='salesman',
            field=models.ForeignKey(limit_choices_to={'role': 'MGMT'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
