# Generated by Django 4.0.4 on 2022-08-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_customer_salesman_alter_event_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
